import type { ScaffoldTheme } from '@/services/presentationScaffolds/types';

export const EXECUTIVE_EDITORIAL_THEMES: ScaffoldTheme[] = [
  {
    id: 'executive',
    label: 'Executive',
    directionId: 'executive',
    bestFor: ['board updates', 'leadership briefings', 'decision memos'],
    colorTheme: { background: '#f8f6f0', primary: '#1f4f63', accent: '#c7663b' },
    backgroundColor: '#f8f6f0',
    tokens: {
      '--pes-bg': '#f8f6f0',
      '--pes-surface': '#ffffff',
      '--pes-ink': '#161616',
      '--pes-muted': '#5f6672',
      '--pes-primary': '#1f4f63',
      '--pes-accent': '#c7663b',
      '--pes-secondary': '#4c7f73',
      '--pes-line': '#d9ded8',
      '--pes-soft': '#edf1ee',
      '--pes-hero-bg': '#111827',
      '--pes-hero-ink': '#f8fafc',
      '--pes-hero-muted': '#cbd5e1',
    },
    moodBySkeleton: {
      cover: 'hero-dark',
      context: 'light',
      'metric-proof': 'light',
      comparison: 'light',
      'mechanism-process': 'dark',
      'closing-action': 'hero-light',
    },
  },
  {
    id: 'launch',
    label: 'Launch',
    directionId: 'launch',
    bestFor: ['go-to-market plans', 'product launches', 'pitch narratives'],
    colorTheme: { background: '#11121a', primary: '#ffffff', accent: '#f59e0b' },
    backgroundColor: '#11121a',
    tokens: {
      '--pes-bg': '#fff7ed',
      '--pes-surface': '#ffffff',
      '--pes-ink': '#191724',
      '--pes-muted': '#6f6470',
      '--pes-primary': '#6d28d9',
      '--pes-accent': '#f97316',
      '--pes-secondary': '#0f766e',
      '--pes-line': '#eadfd2',
      '--pes-soft': '#fff1df',
      '--pes-hero-bg': '#11121a',
      '--pes-hero-ink': '#fff7ed',
      '--pes-hero-muted': '#fed7aa',
    },
    moodBySkeleton: {
      cover: 'hero-dark',
      context: 'light',
      'metric-proof': 'dark',
      comparison: 'light',
      'mechanism-process': 'light',
      'closing-action': 'hero-dark',
    },
    densityBySkeleton: {
      cover: 'calm',
      'metric-proof': 'balanced',
    },
  },
  {
    id: 'editorial',
    label: 'Editorial',
    directionId: 'editorial',
    bestFor: ['thought leadership', 'brand narrative', 'visual storytelling'],
    colorTheme: { background: '#faf9f6', primary: '#1c1c1c', accent: '#c0392b' },
    backgroundColor: '#faf9f6',
    tokens: {
      '--pes-bg': '#faf9f6',
      '--pes-surface': '#ffffff',
      '--pes-ink': '#1c1c1c',
      '--pes-muted': '#62605c',
      '--pes-primary': '#1c1c1c',
      '--pes-accent': '#c0392b',
      '--pes-secondary': '#3f6f68',
      '--pes-line': '#ded8ca',
      '--pes-soft': '#f0ede5',
      '--pes-hero-bg': '#221f1f',
      '--pes-hero-ink': '#faf9f6',
      '--pes-hero-muted': '#d8d0c2',
    },
    moodBySkeleton: {
      cover: 'hero-light',
      context: 'light',
      'metric-proof': 'light',
      comparison: 'dark',
      'mechanism-process': 'light',
      'closing-action': 'hero-dark',
    },
  },
  {
    id: 'research',
    label: 'Research',
    directionId: 'research',
    bestFor: ['evidence reviews', 'findings summaries', 'technical analysis'],
    colorTheme: { background: '#f8fafc', primary: '#1e3a5f', accent: '#0891b2' },
    backgroundColor: '#f8fafc',
    tokens: {
      '--pes-bg': '#f8fafc',
      '--pes-surface': '#ffffff',
      '--pes-ink': '#172033',
      '--pes-muted': '#596579',
      '--pes-primary': '#1e3a5f',
      '--pes-accent': '#0891b2',
      '--pes-secondary': '#64748b',
      '--pes-line': '#dbe3ee',
      '--pes-soft': '#eef5fb',
      '--pes-hero-bg': '#102033',
      '--pes-hero-ink': '#f8fafc',
      '--pes-hero-muted': '#c6d3e2',
    },
    moodBySkeleton: {
      cover: 'hero-light',
      context: 'light',
      'metric-proof': 'light',
      comparison: 'light',
      'mechanism-process': 'dark',
      'closing-action': 'hero-dark',
    },
    densityBySkeleton: {
      context: 'dense',
      'metric-proof': 'balanced',
      comparison: 'dense',
    },
  },
  {
    id: 'teaching',
    label: 'Teaching',
    directionId: 'teaching',
    bestFor: ['workshops', 'training', 'explainers', 'onboarding'],
    colorTheme: { background: '#ffffff', primary: '#1e293b', accent: '#7c3aed' },
    backgroundColor: '#ffffff',
    tokens: {
      '--pes-bg': '#ffffff',
      '--pes-surface': '#f8fafc',
      '--pes-ink': '#1e293b',
      '--pes-muted': '#64748b',
      '--pes-primary': '#1e293b',
      '--pes-accent': '#7c3aed',
      '--pes-secondary': '#0f766e',
      '--pes-line': '#d6dce7',
      '--pes-soft': '#f1f5f9',
      '--pes-hero-bg': '#20133f',
      '--pes-hero-ink': '#ffffff',
      '--pes-hero-muted': '#ddd6fe',
    },
    moodBySkeleton: {
      cover: 'hero-light',
      context: 'light',
      'metric-proof': 'light',
      comparison: 'light',
      'mechanism-process': 'light',
      'closing-action': 'hero-dark',
    },
  },
];
